"""
qlearning/environment.py
========================
Road-network environment for multi-agent Q-learning.

Implements:
  - Energy consumption  Ec  (Eq. 6)
  - Travel time         Tc  (Eq. 7) with queueing delay (Eq. 8)
  - Charging time            (below Eq. 8)
  - Local congestion    δij  (Eq. 9)
  - Global congestion   δ   (Eq. 10)
  - Reward function          (Eq. 12)
  - Bipartite CS allocation  (Sec. V-A-4)
"""

import numpy as np
import networkx as nx
from scipy.optimize import linear_sum_assignment   # Hungarian algorithm


class RoadNetworkEnv:
    """
    Multi-agent EV routing environment on a weighted road graph.

    Parameters
    ----------
    G          : networkx.Graph  (generated by SG-GAN)
    dist_mat   : (n×n) distance matrix [metres]
    time_mat   : (n×n) travel time matrix [seconds]
    cs_nodes   : list of node indices that are Charging Stations
    params     : merged dict of PHYSICS | EV | CS | QLEARN from config.py
    congestion_level : float in [0,1], fraction of road capacity occupied
    seed       : int
    """

    def __init__(self, G, dist_mat, time_mat, cs_nodes, params, congestion_level=0.50, seed=42):
        self.G   = G
        self.n   = G.number_of_nodes()
        self.dist_mat  = dist_mat          # metres
        self.time_mat  = time_mat          # seconds
        self.cs_nodes  = list(cs_nodes)
        self.p         = params
        self.cong_level = congestion_level
        self.rng   = np.random.default_rng(seed)

        # Build adjacency list for fast neighbour lookup
        self.adj_list = {node: list(G.neighbors(node)) for node in G.nodes()}

        # Capacity C_ij per edge: Poisson mean = cong_level × C_ij
        # Uniform edge capacity (paper assumption)
        self.C_ij = np.full((self.n, self.n), 10.0)

        # Charger occupancy at each CS  (tracks queue length)
        self.cs_queue = {cs: 0 for cs in self.cs_nodes}

        # Global visited-node set S (tracks high-traffic nodes)
        self.S_global = set()

        # Speed m/s
        self.v_ms = self.p["v_kmh"] / 3.6

    # ── Physical / energy helpers (Eq. 6) ─────────────────────────────────────

    def energy_kWh(self, distance_m: float, incline: float = None) -> float:
        """
        Ec = (1/η) * (0.5 ρ Cd A v² + Cr m g v + m g d sin θ)
        Returns energy in kWh.
        """
        ph = self.p
        if incline is None:
            incline = ph["theta"]
        v = self.v_ms
        d = distance_m
        aerodynamic = 0.5 * ph["rho"] * ph["Cd"] * ph["A"] * v**2
        rolling     = ph["Cr"] * ph["m"] * ph["g"] * v
        incline_f   = ph["m"] * ph["g"] * d * np.sin(incline)
        E_joules = (1.0 / ph["eta"]) * (aerodynamic + rolling + incline_f)
        # Convert J → kWh:  1 J = 1/3.6e6 kWh
        # But aerodynamic+rolling are in Watts (force × velocity) — multiply by time
        travel_time_s = d / (v + 1e-9)
        E_joules = (1.0 / ph["eta"]) * (
            (aerodynamic + rolling) * travel_time_s + incline_f
        )
        return E_joules / 3_600_000.0

    # ── Congestion (Eq. 9 & 10) ───────────────────────────────────────────────

    def local_congestion(self, i: int, j: int) -> float:
        """δij = q_ij / C_ij, Poisson q ~ Poisson(cong_level × C_ij)."""
        C = self.C_ij[i, j]
        q = self.rng.poisson(self.cong_level * C)
        q = min(q, C)          # clip to capacity
        return float(q / C)

    def global_congestion(self, active_edges: list) -> float:
        """
        δ = Σ w_ij δ_ij / Σ w_ij   (Eq. 10)
        Uniform weights w_ij = 1.
        """
        if not active_edges:
            return 0.0
        deltas = [self.local_congestion(i, j) for i, j in active_edges]
        return float(np.mean(deltas))

    # ── Travel time (Eq. 7 & 8) ───────────────────────────────────────────────

    def travel_time_s(self, distance_m: float) -> float:
        """Pure movement time d/v."""
        return distance_m / (self.v_ms + 1e-9)

    def queueing_delay_s(self, cs_node: int) -> float:
        """
        Little's Law: W = L / λ
        L = current queue length at CS, λ = mean arrival rate.
        """
        L = self.cs_queue.get(cs_node, 0)
        lam = self.p["lambda_arr"] / 3600.0    # convert to per-second
        return L / (lam + 1e-9)

    def charging_time_s(self, soc_current_kWh: float) -> float:
        """
        T_charge = (B_max - B_current) / η_s
        Returns time in seconds.
        """
        B_max     = self.p["battery_kWh"]
        deficit   = max(0.0, B_max - soc_current_kWh)
        eta_s_kW  = self.p["eta_s"]
        return (deficit / eta_s_kW) * 3600.0   # hours → seconds

    def total_travel_time_s(self, distance_m: float,
                             soc_kWh: float, cs_node: int | None) -> float:
        """Eq. 7: Tc = W + d/V + T_charge (if visiting a CS)."""
        t = self.travel_time_s(distance_m)
        if cs_node is not None and soc_kWh < self.p["battery_kWh"]:
            t += self.queueing_delay_s(cs_node)
            t += self.charging_time_s(soc_kWh)
        return t

    # ── Reward (Eq. 12) ───────────────────────────────────────────────────────

    def reward(self, ec_kWh: float, tc_s: float,
               delta_ij: float, reached_dest: bool,
               E_norm: float, T_norm: float) -> float:
        """
        Reward_i = R_base
                   - [β Ec/Enorm + (1-β) Tc/Tnorm] * K_obj
                   - δij/δnorm * K_congestion
                   + I_dest * K_bonus
        """
        p = self.p
        beta     = p["beta"]
        R_base   = p["R_base"]
        K_obj    = p["K_obj"]
        K_cong   = p["K_congestion"]
        K_bonus  = p["K_bonus"]
        delta_norm = 1.0   # maximum δij = 1.0 by definition

        cost = beta * (ec_kWh / E_norm) + (1.0 - beta) * (tc_s / T_norm)
        r = R_base - cost * K_obj - (delta_ij / delta_norm) * K_cong
        if reached_dest:
            r += K_bonus
        return float(r)

    # ── Bipartite CS allocation (Sec. V-A-4, Eq. 17) ─────────────────────────

    def assign_cs_bipartite(self, high_traffic_nodes: list) -> dict:
        """
        Hungarian algorithm to assign high-traffic nodes → nearest available CS.
        Cost = β * ΔE_j/ΔE_norm + (1-β) * W_j/W_norm  (Eq. 17)
        Returns {node: cs_node} mapping.
        """
        if not high_traffic_nodes or not self.cs_nodes:
            return {}

        beta    = self.p["beta"]
        n_ht    = len(high_traffic_nodes)
        n_cs    = len(self.cs_nodes)

        # Cost matrix: rows = high-traffic nodes, cols = CS nodes
        cost_mat = np.zeros((n_ht, n_cs))
        for r, ht_node in enumerate(high_traffic_nodes):
            for c, cs in enumerate(self.cs_nodes):
                dist_to_cs = self.dist_mat[ht_node, cs]
                E_extra    = self.energy_kWh(dist_to_cs)
                W_j        = self.queueing_delay_s(cs)
                cost_mat[r, c] = beta * E_extra + (1.0 - beta) * (W_j / 3600.0)

        # Normalise
        E_max = cost_mat[:, :].max() + 1e-9
        cost_mat /= E_max

        row_ind, col_ind = linear_sum_assignment(cost_mat)
        return {high_traffic_nodes[r]: self.cs_nodes[c]
                for r, c in zip(row_ind, col_ind)}

    # ── SOC critical threshold (paper Sec. VI) ────────────────────────────────

    def soc_critical_kWh(self) -> float:
        """Energy buffer proportional to battery size (2.5 kWh for 10 kWh)."""
        ratio = self.p["energy_buffer_kWh"] / 10.0
        return ratio * self.p["battery_kWh"]
